### ISSUE TITLE
Navigation is a pain with Navigation Compose API

### ISSUE THREAD

**Issue by ksharma-xyz** [ksharma-xyz/Krail#149]
I would really like to pass some data around different screens such as `StopItem`, but need to implement `Parcelable` for all data types used.

```kotlin
data class StopItem(
    val stopName: String,
    val transportModes: ImmutableSet<TransportModeType> = persistentSetOf(),
    val stopId: String,
): Serializable
```

```
FATAL EXCEPTION: main (Ask Gemini)
                        Process: xyz.ksharma.krail.debug, PID: 11280
                        android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = xyz.ksharma.krail.trip_planner.ui.state.searchstop.model.StopItem)
                        	at android.os.Parcel.writeSerializable(Parcel.java:2907)
                        	at android.os.Parcel.writeValue(Parcel.java:2673)
                        	at android.os.Parcel.writeValue(Parcel.java:2472)
                        	at android.os.Parcel.writeList(Parcel.java:1453)
                        	at android.os.Parcel.writeValue(Parcel.java:2616)
                        	at android.os.Parcel.writeValue(Parcel.java:2472)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at android.os.Parcel.writeValue(Parcel.java:2589)
                        	at android.os.Parcel.writeValue(Parcel.java:2479)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at android.os.Parcel.writeValue(Parcel.java:2589)
                        	at android.os.Parcel.writeValue(Parcel.java:2479)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at androidx.navigation.NavBackStackEntryState.writeToParcel(NavBackStackEntryState.kt:73)
                        	at android.os.Parcel.writeParcelable(Parcel.java:2694)
                        	at android.os.Parcel.writeParcelableArray(Parcel.java:4507)
                        	at android.os.Parcel.writeValue(Parcel.java:2637)
                        	at android.os.Parcel.writeValue(Parcel.java:2472)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at android.os.Parcel.writeValue(Parcel.java:2589)
                        	at android.os.Parcel.writeValue(Parcel.java:2479)
                        	at android.os.Parcel.writeList(Parcel.java:1453)
                        	at android.os.Parcel.writeValue(Parcel.java:2616)
                        	at android.os.Parcel.writeValue(Parcel.java:2472)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at android.os.Parcel.writeValue(Parcel.java:2589)
                        	at android.os.Parcel.writeValue(Parcel.java:2479)
                        	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1336)
                        	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1844)
                        	at android.os.Bundle.writeToParcel(Bundle.java:1390)
                        	at android.os.Parcel.writeBundle(Parcel.java:1405)
                        	at android.os.Parcel.writeValue(Parcel.java:2589)
                        	at android.os.Parcel.writeValue(Parcel.java:2479)
                        	at android.os.BaseBundle.dumpStats(BaseBundle.java:1918)
                        	at android.os.BaseBundle.dumpStats(BaseBundle.java:1955)
                        	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
                        	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
                        	at android.os.Handler.handleCallback(Handler.java:959)
                        	at android.os.Handler.dispatchMessage(Handler.java:100)
                        	at android.os.Looper.loopOnce(Looper.java:232)
                        	at android.os.Looper.loop(Looper.java:317)
                        	at android.app.ActivityThread.main(ActivityThread.java:8592)
                        	at java.lang.reflect.Method.invoke(Native Method)
                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                        Caused by: java.io.NotSerializableException: kotlinx.collections.immutable.implementations.persistentOrderedSet.PersistentOrderedSet
                        	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
                        	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620) (Ask Gemini)
                        	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
                        	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
                        	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                        	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
                        	at android.os.Parcel.writeSerializable(Parcel.java:2902)
```

**Comment by ksharma-xyz** [comment]
Probably using https://github.com/slackhq/circuit is a good idea, but that would mean using MVP? Need to explore

**Comment by ksharma-xyz** [comment]
As a temporary workaround will serialize the concrete data types into JSON format and then deserialize them back into their original concrete types.

```kotlin
val fromStopItem: StopItem? = backStackEntry.savedStateHandle.get<String>(SearchStopFieldType.FROM.key)
        ?.let { fromJsonString(it) }
val toStopItem: StopItem? = backStackEntry.savedStateHandle.get<String>(SearchStopFieldType.TO.key)
        ?.let { fromJsonString(it) }
```

**Comment by ksharma-xyz** [comment]
Two major issues with using Navigation Compose API:

- Cannot pass around data
- Need lot of boiler plate logic to pass around data

**Comment by ksharma-xyz** [comment]
Another problem:

I had to create two different variables for saving one thing. In this PR https://github.com/ksharma-xyz/Krail/pull/168 , 

```kotlin
// This holds Arguments value
val fromArg = backStackEntry.savedStateHandle.get<String>(SearchStopFieldType.FROM.key)?.let { fromJsonString(it) }
val toArg = backStackEntry.savedStateHandle.get<String>(SearchStopFieldType.TO.key)?.let { fromJsonString(it) }

// This holds state value for Screen
var fromStopItem: StopItem? by rememberSaveable { mutableStateOf(fromArg) }
var toStopItem: StopItem? by rememberSaveable { mutableStateOf(toArg) }
```
The first variable `fromArg` represents the argument, and the second variable `fromStopItem` represents the state.

1. It is harder to do this reverse stop feature logic if I need to update the state inside viewmodel as well.

When reverse button is clicked, then the data has to be changed twice because of two variables requirement.
  ```kotlin
Timber.d("onReverseButtonClick:")
val bufferStop = fromStopItem
backStackEntry.savedStateHandle[SearchStopFieldType.FROM.key] = toStopItem?.toJsonString()
backStackEntry.savedStateHandle[SearchStopFieldType.TO.key] = bufferStop?.toJsonString()

fromStopItem = toStopItem
toStopItem = bufferStop
```

**Comment by ksharma-xyz** [comment]
Exploring Circuit here - https://github.com/ksharma-xyz/Circuit-Demo

**Comment by ksharma-xyz** [comment]
App Crashes when calling popBackStack(), even when there are more entries in the back stack the app will crash for some devices especially Samsung S23 and S23 Ultra.

Take 1 - https://issuetracker.google.com/issues/340202286?pli=1
Take 2- https://issuetracker.google.com/issues/375343407?pli=1
Take 3 - https://issuetracker.google.com/issues/384186542

>           Fatal Exception: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
>        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
>        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
>        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
>        at java.util.Objects.checkIndex(Objects.java:359)
>        at java.util.ArrayList.get(ArrayList.java:434)
>        at androidx.navigation.compose.NavHostKt$NavHost$28$1.invokeSuspend(NavHost.kt:611)
>        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
>        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
>        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
>        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
>        at android.os.Handler.handleCallback(Handler.java:958)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:230)
>        at android.os.Looper.loop(Looper.java:319)
>        at android.app.ActivityThread.main(ActivityThread.java:9063)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by ksharma-xyz** [comment]
New Navigation Library?
https://android-review.googlesource.com/c/platform/frameworks/support/+/3340914/1

**Comment by ksharma-xyz** [comment]
Nav3 actually looks great from KMP perspective. keep exploring.

**Comment by ksharma-xyz** [comment]
https://insert-koin.io/docs/reference/koin-compose/navigation3/

**Comment by ksharma-xyz** [comment]
Loving navigation 3 😍  https://github.com/ksharma-xyz/KRAIL/pull/1262
